#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ "$DISABLE_LINT_STAGED" != "" ]; then
  echo "Lint staged disabled via env var DISABLE_LINT_STAGED";
  exit 0;
fi;

PATH=./node_modules/.bin:$PATH
lint-staged
