name: Checks

on: [pull_request]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  checks:
    name: All Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Node Version
        run: |
          echo "NODE_VERSION=$(jq -r .engines.node package.json)" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm

      - name: Get pnpm store directory
        id: pnpm-store
        run: |
          echo "PNPM_STORE_DIR=$(pnpm store path)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.PNPM_STORE_DIR }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install

      - name: Test
        run: pnpm jest --color --maxWorkers=2

      - name: Integration
        run: pnpm jest --integration --color --maxWorkers=2

      - name: Access To Node Bins
        run: echo "${GITHUB_WORKSPACE}/node_modules/.bin" >> $GITHUB_PATH
