name: Checks

on: [pull_request]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  quick-checks:
    name: ${{ matrix.runs-on }}
    uses: ./.github/workflows/run-checks.yml
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
    with:
      runs-on: ${{ matrix.runs-on }}
