name: Checks

on: [pull_request]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  quick-checks:
    name: ${{ matrix.os }}
    uses: ./.github/workflows/run-checks.yml
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    with:
      os: ${{ matrix.os }}
