name: Checks

on: [pull_request]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  quick-checks:
    uses: ./.github/workflows/run-checks.yml
    strategy:
      matrix:
        os: [ubuntu-latest]
    with:
      os: ${{ matrix.os }}

  extra-checks:
    uses: ./.github/workflows/run-checks.yml
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    with:
      os: ${{ matrix.os }}
