name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-checks:
    name: ${{ matrix.os }}
    uses: ./.github/workflows/run-checks.yml
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    with:
      os: ${{ matrix.os }}

  release:
    name: Release
    uses: ./.github/workflows/run-release.yml
