name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Node Version
        run: |
          echo "NODE_VERSION=$(jq -r .engines.node package.json)" >> $GITHUB_ENV
          echo "PNPM_VERSION=$(jq -r .engines.pnpm package.json)" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        run: npm i pnpm@${{ env.PNPM_VERSION }} -g

      - name: Setup pnpm Config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install Dependencies
        run: pnpm install

      - name: Test
        run: pnpm turbo run test

      - name: Integration
        run: pnpm turbo run integration

      - name: Create and Publish Versions
        uses: changesets/action@master
        with:
          commit: 'chore: update versions'
          title: 'chore: update versions'
          version: changeset version && pnpm install
          publish: pnpm turbo run build && changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: NOT_SPECIFIED_ON_PURPOSE
