name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-checks:
    name: ${{ matrix.runs-on }}
    uses: ./.github/workflows/run-checks.yml
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
    with:
      runs-on: ${{ matrix.runs-on }}

  release:
    name: Release
    uses: ./.github/workflows/run-release.yml
    needs: [release-checks]
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # @note Using Personal Access Token here to ensure
      # the creation of the PR triggers Checks workflows
      # as was observed with this PR
      # https://github.com/zaripych/repka/pull/34
      # the checks wouldn't be triggered otherwise
      GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
