name: Checks

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  checks:
    name: Checks
    timeout-minutes: 30
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Node Version
        run: |
          echo "NODE_VERSION=$(jq -r .engines.node package.json)" >> $GITHUB_ENV
          echo "NODE_VERSION=$(jq -r .engines.node package.json)" >> "$Env:GITHUB_ENV"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm

      - name: Get pnpm store directory
        id: pnpm-store
        run: |
          echo "PNPM_STORE_DIR=$(pnpm store path)" >> $GITHUB_ENV
          echo "PNPM_STORE_DIR=$(pnpm store path)" >> "$Env:GITHUB_ENV"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.PNPM_STORE_DIR }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install

      - name: Test
        run: pnpm jest --color --maxWorkers=2

      - name: Integration
        run: pnpm jest --integration --color --maxWorkers=2
        env:
          LOG_LEVEL: debug
