name: Checks

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string

      node-version:
        required: false
        type: string

    secrets:
      NPM_TOKEN:
        required: true

jobs:
  release:
    name: Release
    timeout-minutes: 5
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}

    steps:
      - name: Checkout And Install
        uses: zaripych/repka/.github/actions/checkout-and-install@checkout-and-install-latest
        with:
          node-version: ${{ inputs.node-version }}

      - name: Build
        shell: bash
        run: pnpm -r --filter @repka-kit/ts... "/build:tools|declarations/"

      - name: Test NODE_AUTH_TOKEN
        shell: bash
        run: >-
          [ -z "$NODE_AUTH_TOKEN" ] &&  echo "NODE_AUTH_TOKEN is not set" ||
          echo "NODE_AUTH_TOKEN is set"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create and Publish Versions
        uses: changesets/action@v1
        with:
          commit: 'chore: update versions'
          title: 'chore: update versions'
          version: pnpm run ci:version
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
