name: Checks

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string

      node-version:
        required: false
        type: string

jobs:
  release:
    name: Release
    timeout-minutes: 5
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}

    steps:
      - name: Checkout And Install
        uses: zaripych/repka/.github/actions/checkout-and-install@checkout-and-install-v1
        with:
          node-version: ${{ inputs.node-version }}

      - name: Build
        shell: bash
        run: pnpm -r build:tools

      - name: Create and Publish Versions
        uses: changesets/action@v1
        with:
          commit: 'chore: update versions'
          title: 'chore: update versions'
          version: pnpm run ci:version
          publish: pnpm run ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
