name: Checks

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string

      node-version:
        required: false
        type: string

jobs:
  checks:
    name: Checks
    timeout-minutes: 30
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Node Version
        id: node-version
        shell: bash
        run: |
          echo "version=$(jq -r .engines.node package.json)" >> "$GITHUB_OUTPUT"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version:
            ${{ inputs.node-version || steps.node-version.outputs.version }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm

      - name: Get pnpm store directory
        id: pnpm-store
        shell: bash
        run: |
          echo "dir=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-store.outputs.dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install

      - name: Test
        run: pnpm jest --color --maxWorkers=2

      - name: Integration
        run: pnpm jest --integration --color --maxWorkers=2
        env:
          LOG_LEVEL: debug
          TEST_ROOT_DIR: ${{ github.workspace }}/../
